export default {
  canvasTools: {
    exportImage: 'EventTrigger_ExportCanvasAsImage',
    exportPDF: 'EventTrigger_ExportCanvasAsPDF',
    stickyNote: 'EventTrigger_StickyNote',
    rectangle: 'EventTrigger_Rectangle',
    textbox: 'EventTrigger_Textbox',
    circle: 'EventTrigger_Circle',
    drawing: 'EventTrigger_Drawing',
    drawingChangeWidth: 'EventTrigger_DrawingChangeWidth',
    drawingChangeColor: 'EventTrigger_DrawingChangeColor',
    clear: 'EventTrigger_Clear',
    setRemoveObjectEventListener: 'EventTrigger_RemoveObjectEventListener',
    sendCustomModified: 'EventTrigger_customModified',
    enliven: 'EventTrigger_Enliven',
    stickyNoteEnliven: 'EventTrigger_stickyNoteEnliven',
    stickyNoteFontResize: 'EventTrigger_stickyNoteFontResize',
    deletedObejctFromServer: 'EventTrigger_deletedObejctFromServer',
    updateObjectFromServer: 'EventTrigger_updateObjectFromServer',
    CloseAllWhiteBoardControls: 'EventTrigger_CloseAllWhiteBoardControls',
    updatingDataState: 'EventTrigger_UpdatingState',
  },
};
